In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[5]

5

In [5]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [11]:
arr1 = arr[:5]

In [12]:
arr1

array([0, 1, 2, 3, 4])

In [13]:
arr2 = arr[5:]

In [14]:
arr2

array([ 5,  6,  7,  8,  9, 10])

In [15]:
np.append(arr1, arr2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr[0:5] = 100

In [18]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [20]:
arr = np.arange(0, 11)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
slice_of_array = arr[0:6]

In [23]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [24]:
slice_of_array[:] =99

In [25]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [26]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr_copy = arr.copy()

In [28]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [29]:
arr_copy[:] = 8

In [30]:
arr_copy

array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8])

In [31]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [39]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [40]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [41]:
arr_2d[0][0]

5

In [42]:
arr_2d[1,2]

30

In [48]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])